language: node_js
node_js:
  - "7"
script:
 - echo "Deploy!!"
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --project portfolio-app-5ad6d --token 1/vf7YQh910j_QaROxCb_VaTa8fClCTae5s-s_jGJYwVg